server:
  port: 8800

logging:
  level:
    ROOT: INFO
  pattern:
    console: "%d{HH:mm:ss} %clr(%-5p) %clr(:){faint} %clr(%m){faint}%n"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/auth/realms/wheremydocs

  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit

      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:54322/wheremydocs_customer
    username: postgres
    password: 8yR13
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10