server:
  port: 8080

spring:
  data:
    web:
      pageable:
        max-page-size: 200

  application:
    name: customer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth.server.url}

  profiles:
    active: loc

  datasource:
    platform: postgres

  jpa:
    properties:
      org:
        hibernate:
          envers:
            default_schema: audit
    database: postgresql
    open-in-view: true

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      enabled: true
      discovery:
        enabled: true
        register-health-check: true
        health-check-path: /actuator/health
        prefer-ip-address: true
        heartbeat:
          enabled: false
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        tags:
          - profile=${spring.profiles.active}
